### ISSUE TITLE
how to enable packet logger 

### ISSUE THREAD

**Issue by Maoie86** [jpmeijers/ttn-resin-gateway-rpi#11]
I tried setting logger = true in the global_conf.json but it still says packet logger disabled.  also, how do we enable wathdog?

**Comment by jpmeijers** [comment]
How did you set this setting in the `conf` file? Manually via the console terminal?

I see the latest PR added a config line to specify a logfile path:
`gateway_conf['stat_file'] = 'loragwstat.json'`

But I think one still need to enable logging, but that is not added to the `run.py` script yet.

**Comment by Maoie86** [comment]
ok. i modified run.py to enable logging! thanks! :)

**Comment by jpmeijers** [comment]
Can you show me what it looks like with your change? I want to include the change in this repo.

**Comment by Maoie86** [comment]
hi, i just added these lines right after the statement about the stat_file.  it checks the environment variable an assigns that to the logger.  i think watchdog and monitor can be started this way. 

if(os.getenv('GW_LOGGER', "false")=="true"):
  gateway_conf['logger'] = True  
else:
  gateway_conf['logger'] = False

**Comment by jpmeijers** [comment]
Perfect. Thanks!
