### ISSUE TITLE
GW_GPS = true does not enable GPS in local_conf.json

### ISSUE THREAD

**Issue by LX3KR** [jpmeijers/ttn-resin-gateway-rpi#2]
Default GPS setting is:

     }
        ],
        "contact_email": "***********@gmail.com",
        "fake_gps": true,
        "ref_longitude": xxxxxxxxx,
        "ref_latitude": xxxxxxxxxx,
        "gps": true
    }

With environment variable GW_GPS = true local_conf.json is changed to:

 ],
        "contact_email": "***********@gmail.com",
        "fake_gps": false,
        "gps": false
    }

Fake gps is correctly changed to false but gps is also false, surely this should be true?

**Comment by jpmeijers** [comment]
There was a bug with this until last week, when I fixed it with a commit. Are you using the latest version of this repository?

**Comment by LX3KR** [comment]
Hi, just upgraded and it works fine now, thanks for the quick response and thanks for the great software!
Next time I'll check the commit list before submitting an issue.

Thanks again,

Karl Reddy
Rosport, Luxembourg
