### ISSUE TITLE
Not stable with Raspberry 3 ic880a

### ISSUE THREAD

**Issue by tho-wa** [jpmeijers/ttn-resin-gateway-rpi#21]
I have a gateway running with Raspberry 3 ic880a.
I works well for <1h and I receive all packets of my node (sending every 5 minutes, abp) 
But later, I have no more packets in the traffic view of gateway and in the application.
If I reboot the Gatway, I receive the next packet from my node when its send and it works again for a while.
I have no error messages in resin.io besides some random CRC failed packages. 
What should I check?

**Comment by jpmeijers** [comment]
The only stability issues that I have experienced was temperature related. I therefore enabled the Prometheus exporter so that I can monitor the metrics over time. 

You can also try decreasing the SPI speed and see if that helps:
`SPI_SPEED optional - default 8000000` can be lowered to say `1000000`.

**Comment by tho-wa** [comment]
Its a service variable? I will try. 
Strange thing is it directly works after reboot, so guess not temperature.

**Comment by tho-wa** [comment]
Also If I only restart the application container it works for 30-60minutes and then I have the CRC failed packets again. Also lowering Raspberry CPU speed to 600mhz did not change the bevaiour.

**Comment by tho-wa** [comment]
I have now also the power supply to original Raspberry PI 2,5A. 
No change. Still only CRC fail after 15-40minutes of runtime.

**Comment by tho-wa** [comment]
Today I could no more connect to the router: 

04.09.18 12:09:44 (+0200) main 10:09:44 ERROR: [TTN] Connection to server “bridge.eu.thethings.network” failed, retry in 120 seconds
04.09.18 12:09:44 (+0200) main src/ttn_transport.c:371:ttn_connect(): ttn_connect: sleeping() at 0, total 120
04.09.18 12:09:54 (+0200) main src/ttn_transport.c:371:ttn_connect(): ttn_connect: sleeping() at 10, total 120
04.09.18 12:10:04 (+0200) main src/ttn_transport.c:371:ttn_connect(): ttn_connect: sleeping() at 20, total 1

I switched to “Router digitalcatapult-uk-router” in the Gateways settings.
Besides the connection problem, now also my stability issue for weeks seems to be solved.
Seems it was not toiC880 related, connection to TTN handler have cause this problems after some runtime. Works now stable for whole day. 
CRCs maybe only environment noise.

**Comment by tho-wa** [comment]
Seems to be related to the backend.
