### ISSUE TITLE
WARNING: invalid configuration for Lora standard channel

### ISSUE THREAD

**Issue by systemeintegratedsolutions** [jpmeijers/ttn-resin-gateway-rpi#5]
**Setup**

- Raspberry-pi 3
- RisingHF Dicovery IOT radio kit 

I follow your guide to the letter but I get the sense I am missing something. My gateway is connected to TTN via resin.io process , but I get a message saying "WARNING: invalid configuration for Lora standard channel".

I am struggling to get a Feather Lora 32u4 board to act as a node, but that's a seperate issue :P I want to focus on making sure that my radio kit is correct because when I run the node, it get's stuck on 'Joining' and appears to time-out so I suspect that the gateway radio is not configured correctly. 

The log files tells me that it cannot start the concentrator. Log file attached. I get the sense that the RF module is incorrect, but I don't have any idea where I can change it. I was under the impression that my module uses a 'sx1276' radio, but the log file mentions 'sx1301' ?! 
[ttngw_lingering-sky-13.09.17_22-19-07_(+0200).txt](https://github.com/jpmeijers/ttn-resin-gateway-rpi/files/1300922/ttngw_lingering-sky-13.09.17_22-19-07_.0200.txt)

**Comment by jpmeijers** [comment]
I see you are using the Australian frequency plan. There was in fact an issue with the standard channel, and was just fixed: https://github.com/TheThingsNetwork/gateway-conf/issues/22

From the log file everything seems ok. It however doesn't show any received packets. Maybe your Feather isn't transmitting on the correct frequencies.

The gateway makes use of an sx1301, while the end-device uses the sx1276.
