### ISSUE TITLE
Risinghf0m301 Reset Pin Wrong

### ISSUE THREAD

**Issue by kinasmith** [jpmeijers/ttn-resin-gateway-rpi#6]
The correct reset pin number for this board is 25, not 26.

**Comment by jpmeijers** [comment]
Are you using this breakout board: http://www.risinghf.com/product/risinghf-iot-dicovery/?lang=en

Physical pin nr 25 is a ground pin on the Raspberry Pi header (https://pinout.xyz/) which makes it impossible to be a reset pin.

Other users confirmed that the reset pin for the RHF0M301 is BCM7 which is equal to physical pin nr 26.

Please let us know if we are missing anything.
